### ISSUE TITLE
Does this only work up to 524288 triangles?

### ISSUE THREAD

**Issue by Pjbomb2** [drzhn/UnityBVHConstruction#1]
Hey, more of a question before I go through the effort of porting it to my own project(want to compare its tracing performance to the CWBVH I currently use as the fast builds are tremendously attractive), but I noticed that Constants.cs has the DATA_ARRAY_COUNT set to 524288, so was this the max triangle count the LBVH builder can handle at once?

**Comment by drzhn** [comment]
Correct. I did it for testing reasons (triangle count in the sponza scene in [another project](https://github.com/drzhn/JoyEngineDX12) fit in this limit) and I was too lazy to test this project for other triangle limits. You can change BLOCK_SIZE in Constants.cs and Constants.cginc to increase DATA_ARRAY_COUNT value, but do it at your own risk
